Blog-Application: Add authorization rules 📐
Obimbo07/tdn pull request #12
Opened 2024-02-02 16:07 UTC by evansnyamekye

- Install CanCanCan in your project.
- Add a role column to the user's table. Remember to use a migration for this.
A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- [ ] For that you need to implement the post-deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- [ ] For that you need to implement the comment deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.

@evansnyamekye 
@Obimbo07 
@Izebiafe 

Thank you 👨👨👨

2024-02-02 17:11 UTC, zeff96 reviewed
## STATUS: INVALID CODE REVIEW 🛑
Hi @evansnyamekye, @Obimbo07 and @Izebiafe , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that lacks equal contribution into the codebase from all partners, @Izebiafe kindly make sure to have fair contribution. Please go ahead and close this PR without merging and open a new PR with equal commits from all partners

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-02-03 12:26 UTC, fobadara requested changes
Hi team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-03 12:26 UTC, fobadara commented on app/controllers/posts_controller.rb
[REQUIRED] Kindly use CanCan for post authorization. You can do this:
```
class PostsController < ApplicationController
    load_and_authorize_resource

    ...
  end
```

2024-02-03 16:57 UTC, skyv26 requested changes
## Hi @evansnyamekye, @fobadara and @Izebiafe, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjBkZWI1YTgxNDg4Y2QzMWU2MjkyNjQ2MmY1MmIzMjM4ZmI1MGU1OCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fDWHJAmgrCeIw/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implemented the features ✅ 
- Nice *UI* design ✅

## Required Changes ♻️

- [ ] Dear Team members, you did a great job so far, but it seems like you missed some core project requirements, according to which you should add the functionalities to delete `post` and `comments`. Only in two conditions, it should work, either a person who is authorized as an `admin` can delete any `post` and `comment` of any user **OR** a normal user can delete its own `posts` or `comments` on the blog. Right now, the add comments, like. delete button all these are missing in your project and because it is a part of requirement, which needs to fulfill in order to pass the milestone. Kindly take a look at the below screenshot and do the things accordingly before asking for the next review.

![image](https://github.com/Obimbo07/tdn/assets/66476329/73d56890-d431-4424-8d6d-372b7e166a42)


_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-03 16:57 UTC, skyv26 commented on app/controllers/posts_controller.rb
- [ ] Please adhere to the project requirements, your previous code reviewer asked for the adding the `callback` attribute `load_and_authorize_resource` to auto load the `authorization` for the posts. But it seems like you didn't add it, kindly add the required changes and re-submit your project again.

2024-02-03 20:46 UTC, Obimbo07 commented on app/controllers/posts_controller.rb
We Resolved the posts authorization

2024-02-03 21:11 UTC, shahadat3669 requested changes
Hi every one, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-03 21:11 UTC, shahadat3669 commented on app/views/posts/show.html.erb
> +          <% end %>
- [ ] Great work so far! However, I noticed that there is an issue with the comment functionality. When I tried to delete a comment as a user or admin, it did not work as expected. I received an `ActiveRecord::RecordNotFound` error in the console for the comment. Additionally, I noticed that the code is checking for a post with ID 3 (while the post ID was 4) in line number 20 of your controller. So I was unable to test the authorization. To fix this issue, I recommend that you update your code and use the proper parameters for it.

2024-02-03 21:11 UTC, shahadat3669 commented on app/controllers/posts_controller.rb
- [ ] Great job so far! Your post-delete controller is working properly. However, as the previous reviewer mentioned, please add 'load_and_authorize_resource' before all of your controller methods.

```ruby
 class PostsController < ApplicationController
    load_and_authorize_resource

    ...
  end
```

2024-02-03 22:34 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - load_and_authorize_resource to post controller ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-03 22:34 UTC, prolajumokeoni commented on app/views/users/show.html.erb
>    <%= link_to "See all posts",user_posts_path(@user), class: "button" %>
### OPTIONAL
 
 - Good job so far, when I click the see all post I see this error ⬇️ 
![Screenshot_243](https://github.com/Obimbo07/tdn/assets/69638013/def736cd-cf7d-416c-8da9-c8939f88abd5)

- [ ] You can update your code to show a popup of `no posts yet` and add a button for users to create a new post,  on each user's profile 👍🏿

2024-02-03 22:35 UTC, merged