Feature Controller
Obimbo07/tdn pull request #6
Opened 2024-01-16 13:57 UTC by Obimbo07

In this pull request the following is tested:

- If response status was correct.
- if a correct template was rendered.
- If the response body includes correct placeholder text.

2024-01-16 14:31 UTC, julie-ify requested changes
## Hi @Obimbo07,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 14:31 UTC, julie-ify commented on spec/requests/posts_spec.rb
> +    end
- [ ] Kindly organize your specs. This it-block is for the index posts page and so should be under the `GET /index` describe block above.

2024-01-16 14:31 UTC, julie-ify commented on spec/requests/users_spec.rb
> +    end
- [ ] Kindly organize your specs. This it-block is for the index posts page and so should be under the `GET /index` describe block above.

2024-01-16 14:31 UTC, julie-ify commented on spec/requests/users_spec.rb
> +    it 'render the show template for post' do
- [ ] Kindly fix your failing specs. You need to install the `rails-controller-testing` gem as indicated by the error message.

  ![image](https://github.com/Obimbo07/tdn/assets/81468675/2eff75fb-5e7b-40f3-87f7-a7991da1ef5e)

2024-01-16 14:31 UTC, julie-ify commented on spec/requests/posts_spec.rb
> +      get user_post_path(user)
- [ ] After adding the gem to Gemfile and running the bundler, this test still fails. You need to specify the correct route: `user_posts_path(user)`

  ![image](https://github.com/Obimbo07/tdn/assets/81468675/8aa0547e-55f4-4490-8591-ad4cc7bdd0a5)

2024-01-18 13:52 UTC, Reem-lab approved these changes
# Hi @Obimbo07,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Descriptive PR⭐
- [ ]  No Linters error 🤩
- [ ] Good job working on the testsI💪🏻
- [ ] All tests passed🔥🔥


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 14:08 UTC, merged